create table if not exists public.whiteboard_corrections (
  id bigint generated by default as identity primary key,
  source_text text not null default '',
  ai_title text not null,
  corrected_title text not null,
  ai_schedule_type text not null default 'unclassified',
  corrected_schedule_type text not null default 'unclassified',
  occurrence_count integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whiteboard_corrections_ai_type_check
    check (ai_schedule_type in ('meeting', 'business_trip', 'internal', 'leave', 'unclassified')),
  constraint whiteboard_corrections_corrected_type_check
    check (corrected_schedule_type in ('meeting', 'business_trip', 'internal', 'leave', 'unclassified')),
  constraint whiteboard_corrections_unique
    unique (ai_title, corrected_title, ai_schedule_type, corrected_schedule_type)
);

alter table public.whiteboard_corrections enable row level security;

create or replace function public.save_whiteboard_corrections(p_corrections jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_count integer := 0;
begin
  if jsonb_typeof(p_corrections) <> 'array' then
    return 0;
  end if;

  insert into public.whiteboard_corrections (
    source_text,
    ai_title,
    corrected_title,
    ai_schedule_type,
    corrected_schedule_type
  )
  select
    left(trim(coalesce(item->>'source_text', '')), 500),
    left(trim(item->>'ai_title'), 200),
    left(trim(item->>'corrected_title'), 200),
    case
      when item->>'ai_schedule_type' in ('meeting', 'business_trip', 'internal', 'leave', 'unclassified')
        then item->>'ai_schedule_type'
      else 'unclassified'
    end,
    case
      when item->>'corrected_schedule_type' in ('meeting', 'business_trip', 'internal', 'leave', 'unclassified')
        then item->>'corrected_schedule_type'
      else 'unclassified'
    end
  from jsonb_array_elements(p_corrections) as item
  where trim(coalesce(item->>'ai_title', '')) <> ''
    and trim(coalesce(item->>'corrected_title', '')) <> ''
    and (
      trim(item->>'ai_title') <> trim(item->>'corrected_title')
      or coalesce(item->>'ai_schedule_type', 'unclassified')
        <> coalesce(item->>'corrected_schedule_type', 'unclassified')
    )
  on conflict (ai_title, corrected_title, ai_schedule_type, corrected_schedule_type)
  do update set
    source_text = excluded.source_text,
    occurrence_count = public.whiteboard_corrections.occurrence_count + 1,
    updated_at = now();

  get diagnostics saved_count = row_count;
  return saved_count;
end;
$$;

revoke all on table public.whiteboard_corrections from anon, authenticated;
revoke all on function public.save_whiteboard_corrections(jsonb) from public;
grant execute on function public.save_whiteboard_corrections(jsonb) to anon, authenticated;

comment on table public.whiteboard_corrections is '화이트보드 AI 분석 결과의 공용 교정 기록';

insert into public.whiteboard_corrections (
  source_text,
  ai_title,
  corrected_title,
  ai_schedule_type,
  corrected_schedule_type
)
values ('방문재난', '방문재난', '방문재활', 'business_trip', 'business_trip')
on conflict (ai_title, corrected_title, ai_schedule_type, corrected_schedule_type)
do update set
  occurrence_count = public.whiteboard_corrections.occurrence_count + 1,
  updated_at = now();
