create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  action text not null,
  record_id text,
  actor_user_id uuid,
  actor_device_name text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now(),
  constraint activity_logs_table_name_check
    check (table_name in ('schedules', 'messages', 'categories', 'files')),
  constraint activity_logs_action_check
    check (action in ('insert', 'update', 'delete'))
);

create index if not exists activity_logs_created_at_idx
  on public.activity_logs (created_at desc);

create index if not exists activity_logs_table_action_idx
  on public.activity_logs (table_name, action, created_at desc);

alter table public.activity_logs enable row level security;

revoke all on table public.activity_logs from public, anon, authenticated;
grant select on table public.activity_logs to authenticated;

drop policy if exists approved_devices_read_activity_logs on public.activity_logs;
drop policy if exists device_approval_required_for_activity_logs on public.activity_logs;

create policy approved_devices_read_activity_logs
on public.activity_logs
as permissive
for select
to authenticated
using (public.is_device_approved());

create policy device_approval_required_for_activity_logs
on public.activity_logs
as restrictive
for select
to authenticated
using (public.is_device_approved());

create or replace function public.capture_activity_log()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor_id uuid := auth.uid();
  actor_name text;
  old_row jsonb;
  new_row jsonb;
  target_record_id text;
begin
  old_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;

  if tg_op = 'UPDATE' and old_row is not distinct from new_row then
    return new;
  end if;

  if actor_id is not null then
    select access.device_name
      into actor_name
    from public.device_access as access
    where access.user_id = actor_id;
  end if;

  target_record_id := coalesce(new_row ->> 'id', old_row ->> 'id');

  insert into public.activity_logs (
    table_name,
    action,
    record_id,
    actor_user_id,
    actor_device_name,
    before_data,
    after_data
  )
  values (
    tg_table_name,
    lower(tg_op),
    target_record_id,
    actor_id,
    actor_name,
    old_row,
    new_row
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

revoke all on function public.capture_activity_log() from public, anon, authenticated;

do $$
declare
  target_table text;
  trigger_name text;
begin
  foreach target_table in array array['schedules', 'messages', 'categories', 'files']
  loop
    if to_regclass(format('public.%I', target_table)) is null then
      raise notice 'Skipping missing table public.%', target_table;
      continue;
    end if;

    trigger_name := format('capture_%s_activity', target_table);
    execute format('drop trigger if exists %I on public.%I', trigger_name, target_table);
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.capture_activity_log()',
      trigger_name,
      target_table
    );
  end loop;
end;
$$;

comment on table public.activity_logs is '공유 대시보드 주요 데이터의 변경 이력. 승인 기기는 읽기만 가능';
comment on column public.activity_logs.before_data is '변경 또는 삭제 전 행의 JSON 스냅샷';
comment on column public.activity_logs.after_data is '생성 또는 변경 후 행의 JSON 스냅샷';

notify pgrst, 'reload schema';
